import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import Image from "next/image";
import BackgroundOverlay from "@/public/hero-background-overlay.svg";
import "./globals.css";

const cairoFont = Cairo({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" className="min-h-screen h-full" suppressHydrationWarning>
      <body className={`${cairoFont.className} antialiased overflow-x-hidden`}>
        <Image
          src={BackgroundOverlay}
          alt="Hero Background Overlay"
          width={900}
          height={900}
          className="absolute top-[-160px] left-[900px] lg:block hidden right-0 bottom-0 -z-10 pointer-events-none select-none"
        />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
